apiVersion: apps/v1
kind: Deployment
metadata:
  name:  timeservice
  labels:
    app:  timeservice
spec:
  selector:
    matchLabels:
      app: timeservice
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  timeservice
    spec:
      containers:
      - name:  timeservice
        image:  jayharnesha007/particle41:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  3000
          name:  timeservice
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      volumes:
        - name: localtime
          hostPath:
            path: /usr/share/zoneinfo/Asia/Kolkata
            type: File
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: timeservice
spec:
  selector:
    app: timeservice
  type: NodePort
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: timeservice
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 32000